export const footer = {
  logo: { src: '/assets/logo-footer.svg', alt: 'GreenMIP' },
  summary: 'Agromonitoreo avanzado. Decisiones rentables basadas en data exacta para cultivos a lo largo de Chile.',
  navTitle: 'Navegación',
  navLinks: [
    { label: 'Servicios', id: 'servicios' },
    { label: 'Cómo funciona', id: 'como-funciona' },
    { label: 'Sobre Isaac Vera', id: 'sobre-isaac' },
    { label: 'Ventajas', id: 'ventajas' },
    { label: 'Contacto', id: 'contacto' },
  ],
  contactTitle: 'Contacto',
  contactPhoneDisplay: '+56 9 3070 7919',
  contactPhoneDial: '+56930707919',
  socials: [
    { label: 'LinkedIn', url: '#' },
    { label: 'Instagram', url: '#' },
  ],
  certificationTitle: 'Certificaciones',
  certificationText: 'Este sitio funciona 100% con energía renovable certificada.',
  certificationImage: { src: '/assets/Certification Seal.svg', alt: 'Sello de certificación Ciclo17' },
  co2Seal: {
    value: '0.3g',
    unitLabel: 'por visita',
    caption: 'Sitio web de bajo impacto ambiental.',
  },
  developedByLabel: 'Sitio Web desarrollado por',
  developedByName: 'Ciclo17.cl',
  developedByUrl: 'https://ciclo17.cl',
};
